# Generated by Django 3.0 on 2021-12-20 14:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='تاريخ المسابقة')),
                ('teams', models.TextField(blank=True, null=True, verbose_name='الفِرق المنافِسة')),
            ],
            options={
                'verbose_name': 'مسابقة',
                'verbose_name_plural': 'مسابقات',
            },
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=200, verbose_name='الاسم الثلاثي باللغة العربية')),
                ('en_name', models.CharField(max_length=200, verbose_name='الاسم الثلاثي باللغة الإنجليزية')),
                ('job', models.CharField(max_length=200, verbose_name='الوظيفة')),
                ('workplace', models.CharField(max_length=200, verbose_name='جهة العمل/الدراسة')),
                ('invention_name', models.CharField(max_length=600, verbose_name='اسم الاختراع')),
                ('inv_category', multiselectfield.db.fields.MultiSelectField(choices=[('anm', 'علوم الحيوان'), ('bhv', 'العلوم الاجتماعية والسلوكية'), ('bch', 'الكيمياء الحيوية'), ('bmd', 'العلوم الطبية الحيوية والصحية'), ('mde', 'الهندسة الطبية الحيوية'), ('cbi', 'الأحياء الخلوية والجزيئية'), ('chm', 'الكيمياء'), ('bit', 'المعلوماتية الحيوية'), ('eco', 'علوم الأرض والبيئة'), ('emb', 'الأنظمة المدمجة'), ('che', 'الطاقة الكيميائية'), ('phe', 'الطاقة الفيزيائية'), ('mch', 'الهندسة الميكانيكية'), ('ene', 'الهندسة البيئية'), ('smt', 'علم المواد'), ('mat', 'الرياضيات'), ('mbi', 'الأحياء الدقيقة'), ('ast', 'الفيزياء والفلك'), ('bot', 'علوم النبات'), ('rai', 'الربوتات والذكاء الاصطناعي'), ('prg', 'الأنظمة البرمجية والبرمجة'), ('mob', 'العلوم الطبية الانتقالية'), ('oth', 'تصنيف آخر')], max_length=91, verbose_name='التصنيف (يمكن اختيار أكثر من تصنيف)')),
                ('other_category', models.CharField(blank=True, max_length=600, null=True, verbose_name="إذا اخترت 'تصنيف آخر'، اذكره هنا ")),
                ('summary', models.TextField(verbose_name='ملخص الاختراع')),
                ('is_prototype', models.BooleanField(verbose_name='هل يوجد لديك نموذج أولي؟')),
                ('prototype_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='الرجاء إرفاق النموذج الأولي كملف PDF إن وجد')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'مخترع',
                'verbose_name_plural': 'مخترعين',
            },
        ),
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('category', models.CharField(max_length=100, verbose_name='الفئة')),
                ('olympiad_version', models.CharField(max_length=100, null=True, verbose_name='نسخة الأولمبياد')),
                ('is_last_main', models.BooleanField(default=False, verbose_name='هل هو السؤال الأخير من الأسئلة الأساسية؟')),
                ('is_extra', models.BooleanField(default=False, verbose_name='هل السؤال إضافي؟')),
                ('contest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='science_olympiad.Contest', verbose_name='المسابقة')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة',
            },
        ),
        migrations.CreateModel(
            name='ContestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الجواب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل الجواب صحيح؟')),
                ('is_excludable', models.BooleanField(default=False, verbose_name='هل يمكن حذف الجواب؟')),
                ('choice_letter', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], default='', max_length=1, verbose_name='حرف الخيار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science_olympiad.ContestQuestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'أجوبة',
            },
        ),
    ]
